CREATE TABLE invoice_db.INVOICE (
    INVOICE_ID VARCHAR(200) NOT NULL,
    USER_ID VARCHAR(200) NOT NULL,
    INVOICE_NUMBER VARCHAR(500) NOT NULL,
    PRODUCT_IDS TEXT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATED_TIME TIMESTAMP NOT NULL,
    constraint INVOICE_ID_PK primary key (INVOICE_ID),
    constraint USER_ID_FK foreign key (USER_ID) references USER_DB.USER_RECORD(USER_ID)
);